name: stylishEcommerceApp

options:
  bundleIdPrefix: com.Softtek
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: "15.0"
  generateEmptyDirectories: false
  fileSystemSynchronizedGroups: true
  defaultSourceDirectoryType: syncedFolder
  useBaseInternationalization: false

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""

targets:
  stylishEcommerceApp:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
    - path: stylishEcommerceApp
      excludes:
        - "*.xcassets"
    resources:
      - path: stylishEcommerceApp/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.Softtek.Stylish-ECommerce-App
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
    
    schemes:
      stylishEcommerceApp:
        build:
          targets:
            stylishEcommerceApp: all
        run:
          config: Debug
        profile:
          config: Release
        analyze:
          config: Debug
        archive:
          config: Release